---
- hosts: all
  tasks:
    - name: create multiple directories in a loop
      file:
           path: $HOME/ansible/test
           state: directory
    - name: remove directory
      file:
           path: $HOME/ansible/test
           state: absent

