---
- hosts: all
  become: true
  become_user: root
  vars:
   password: root
   username: usernme
   userid: usrid
   comments: cmmts
   pgrp: pgrnm
   sgrp: sgrnms
  tasks:
    - name: User Creation
      user: name="{{ username }}" comment="{{ comments }}" uid={{ userid }} password="{{ password }}" group="{{ pgrp }}" groups="{{ sgrp }}" append=yes
