---
- hosts: all
  name: patching tutorial
  become: yes
  become_user: root
  tasks:
    - name: to check apache running or not
      shell: if ps -eaf | grep -i "httpd" | grep -v grep > /dev/null; then echo 'processes running' ; else echo 'not running' ; fi
      ignore_errors: true
      register: check
    - debug: msg="{{ check.stdout }}"
    - name: decision point to start patching
      fail: msg="{{ ansible_hostname }} have running "
      when: check.stdout == "processes running"

