---
- name: Handlers
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Install the Apache service
      yum:
          name: httpd
          state: present
      notify: 
       - restart_apache


  handlers:
  - name: restart_apache
    service:
            name: httpd
            state: restarted
