---
-  hosts: all
   become: yes
   become_user: root
   vars:
    VIM: vim
    Apache: httpd
    stop: stopped
   tasks:
    - name: Using Variables
      yum: name="{{ VIM }}" "{{ Apache }}" state="present"
    - name: stopping httpd service
      service:
        name: "{{ Apache }}"
        state: "{{ stop }}"


      

